import json
import os
import re
import statistics
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq


def stylometric_signal(text: str) -> float:
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = text.lower().split()
    total_words = len(words)
    total_chars = len(text)

    # Sentence length variance score
    if len(sentences) >= 2:
        lengths = [len(s.split()) for s in sentences]
        variance = statistics.variance(lengths)
        variance_score = 1 - min(variance / 400, 1.0)
    else:
        # ponytail: short text edge case — assume uniform (AI-like)
        variance_score = 1.0

    # Type-token ratio score
    if total_words > 0:
        ttr = len(set(words)) / total_words
        ttr_score = 1 - min(ttr / 0.7, 1.0)
    else:
        ttr_score = 0.5

    # Punctuation density score
    if total_chars > 0:
        punct_chars = sum(1 for c in text if c in '!?()—…–')
        density = punct_chars / total_chars
        punct_score = 1 - min(density / 0.05, 1.0)
    else:
        punct_score = 0.5

    return (variance_score + ttr_score + punct_score) / 3


def llm_signal(text: str, groq_client) -> float:
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an AI detection tool. Analyze the given text and return ONLY a "
                        "decimal number between 0.0 and 1.0 representing the probability it was "
                        "generated by AI. 0.0 = definitely human-written. 1.0 = definitely "
                        "AI-generated. Return nothing except the number."
                    ),
                },
                {"role": "user", "content": text[:2000]},
            ],
            temperature=0,
        )
        return float(response.choices[0].message.content.strip())
    except Exception:
        return 0.5


def combine_scores(llm: float, stylo: float) -> float:
    return (0.60 * llm) + (0.40 * stylo)


def generate_label(score: float) -> tuple[str, str]:
    if score < 0.35:
        return (
            "likely_human",
            "This content shows strong indicators of human authorship. The writing "
            "style reflects the natural variation and personal voice consistent with human "
            "writing.",
        )
    elif score <= 0.65:
        return (
            "uncertain",
            "Our system was unable to confidently determine whether this content "
            "was written by a human or AI. This does not indicate a violation — many writing "
            "styles fall in this range. No action has been taken.",
        )
    else:
        return (
            "likely_ai",
            "This content shows strong indicators of AI generation. The writing "
            "style appears notably uniform and lacks the natural variation typical of human "
            "authors. If you wrote this yourself, you can submit an appeal below.",
        )


def write_log(entry: dict) -> None:
    with open("audit_log.json", "a") as f:
        f.write(json.dumps(entry) + "\n")


def read_log(n: int = 20) -> list:
    try:
        with open("audit_log.json") as f:
            lines = [json.loads(line) for line in f if line.strip()]
        return lines[-n:]
    except FileNotFoundError:
        return []


def create_app(config=None):
    load_dotenv()
    app = Flask(__name__)

    groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    content_store = {}

    limiter = Limiter(
        get_remote_address,
        app=app,
        default_limits=[],
        storage_uri=config.get("RATELIMIT_STORAGE_URI", "memory://") if config else "memory://",
    )

    if config:
        app.config.update(config)

    @app.post("/submit")
    @limiter.limit("10 per minute;50 per day")
    def submit():
        data = request.get_json(force=True)
        text = data.get("text", "")
        creator_id = data.get("creator_id", "anonymous")

        llm_score = llm_signal(text, groq_client)
        stylo_score = stylometric_signal(text)
        confidence = combine_scores(llm_score, stylo_score)
        attribution, label_text = generate_label(confidence)
        content_id = str(uuid.uuid4())

        content_store[content_id] = {"status": "classified", "creator_id": creator_id}

        entry = {
            "content_id": content_id,
            "creator_id": creator_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "attribution": attribution,
            "confidence": round(confidence, 4),
            "llm_score": round(llm_score, 4),
            "stylometric_score": round(stylo_score, 4),
            "status": "classified",
            "appeal_reasoning": None,
        }
        write_log(entry)

        return jsonify({
            "content_id": content_id,
            "attribution": attribution,
            "confidence": round(confidence, 4),
            "llm_score": round(llm_score, 4),
            "stylometric_score": round(stylo_score, 4),
            "label_text": label_text,
            "status": "classified",
        })

    @app.post("/appeal")
    def appeal():
        data = request.get_json(force=True)
        content_id = data.get("content_id")
        reasoning = data.get("creator_reasoning", "")

        if content_id not in content_store:
            return jsonify({"error": "Content not found"}), 404

        content_store[content_id]["status"] = "under_review"

        write_log({
            "content_id": content_id,
            "creator_id": content_store[content_id]["creator_id"],
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "attribution": None,
            "confidence": None,
            "llm_score": None,
            "stylometric_score": None,
            "status": "under_review",
            "appeal_reasoning": reasoning,
        })

        return jsonify({
            "message": "Appeal received. Your content is now under review.",
            "content_id": content_id,
            "status": "under_review",
        })

    @app.get("/log")
    def log():
        return jsonify({"entries": read_log()})

    @app.get("/health")
    def health():
        return jsonify({"status": "ok"})

    return app


if __name__ == "__main__":
    create_app().run(debug=True)
